version: "3.9"


services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
#      - POSTGRES_PASSWORD=123jkl
      - POSTGRES_HOST_AUTH_METHOD=trust
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "5430:80"
      - "5431:443"
    environment:
      - PGADMIN_DEFAULT_EMAIL=abhishek.bhardwaj@iongroup.com
      - PGADMIN_DEFAULT_PASSWORD=123jkl
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
  eureka-server:
    build:
      context: ./../prorate-eureka-server
      dockerfile: eureka-server.Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - "postgres"
  ms-doctors:
    build:
      context: ./../prorate-ms-doctors
      dockerfile: ms-doctors.Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - "postgres"

