version: "3.9"


services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
#      - POSTGRES_PASSWORD=123jkl
      - POSTGRES_HOST_AUTH_METHOD=trust
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "5430:80"
      - "5431:443"
    environment:
      - PGADMIN_DEFAULT_EMAIL=abhishek.bhardwaj@iongroup.com
      - PGADMIN_DEFAULT_PASSWORD=123jkl
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
  eureka-server:
    image: abhisheklab49/prorate-eureka-server:latest
    ports:
      - "8761:8761"
    depends_on:
      - "postgres"
  config-server:
    image: abhisheklab49/prorate-config-server:latest
    ports:
      - "8888:8888"
    depends_on:
      - "eureka-server"
  ms-doctors:
    image: abhisheklab49/prorate-ms-doctors:latest
    ports:
      - "8081:8081"
    depends_on:
      - "postgres"
      - "eureka-server"
      - "config-server"
  ms-reviews:
    image: abhisheklab49/prorate-ms-reviews:latest
    ports:
      - "8082:8082"
    depends_on:
      - "postgres"
      - "eureka-server"
      - "config-server"

